title: Himal Ella
remote_theme: jekyll/minima

# This section prevents the "Subscribe" button from generating
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap 

minima:
  skin: dark

header_pages:
  - about.md
  - cv.md
  - contact.md
